CREATE TABLE IF NOT EXISTS `user_base` (
  `name` int(11) NOT NULL DEFAULT '0' COMMENT '玩家账户ID',
  `create_time` int(11) NOT NULL DEFAULT '0' COMMENT '创建的时间',
  `nick_name` varchar(30) NOT NULL DEFAULT '' COMMENT '昵称',
  `level` smallint(3) NOT NULL DEFAULT '1' COMMENT '玩家等级',
  `vip_level` smallint(3) DEFAULT '0' COMMENT 'VIP等级',
  `recharge_gold` int(11) DEFAULT '0' COMMENT '通过充值的水晶',
  `rmb` int(11) DEFAULT '0',
  `recharge_money` float(11,2) DEFAULT '0.00' COMMENT '充值人民币',
  `recharge_money1` float(11,2) DEFAULT '0.00',
  `recharge_money2` float(11,2) DEFAULT '0.00',
  `strongestares_recharge` float(11,2) DEFAULT '0.00',
  `exp` int(11) DEFAULT '0' COMMENT '玩家当前经验',
  `cash` int(11) DEFAULT '0' COMMENT '金币',
  `gold` int(11) DEFAULT '0' COMMENT '水晶',
  `trophy_num` int(11) DEFAULT '0' COMMENT '奖杯个数',
  `month_card_fate` mediumint(9) DEFAULT '0' COMMENT '月卡天数',
  `month_card_fate_1` mediumint(9) DEFAULT '0',
  `month_card_fate_2` mediumint(9) DEFAULT '-1',
  `restriction` varchar(50) DEFAULT '' COMMENT '限购ID',
  `friend_value` int(11) DEFAULT '0' COMMENT '友情点',
  `cur_strength` smallint(6) NOT NULL DEFAULT '100' COMMENT '玩家当前体力值',
  `max_strength` smallint(6) NOT NULL DEFAULT '100' COMMENT '体力值上限',
  `strength_record_time` int(11) NOT NULL DEFAULT '0' COMMENT '体力值回复记录时间',
  `buy_str_count` smallint(6) NOT NULL DEFAULT '0' COMMENT '可购买体力次数',
  `buy_str_count_max` smallint(6) DEFAULT '1' COMMENT '最大可购买次数',
  `add_buystr_count` smallint(6) DEFAULT '0',
  `pvp_matebuy_count` smallint(3) DEFAULT '0' COMMENT '购买PVP次数上限',
  `bag_capacity` mediumint(9) NOT NULL DEFAULT '100' COMMENT '背包容量',
  `equip_capacity` mediumint(9) DEFAULT '100' COMMENT '装备背包上限',
  `friend_capacity` mediumint(9) DEFAULT '10' COMMENT '好友上限',
  `status` tinyint(3) NOT NULL DEFAULT '3' COMMENT '玩家状态，GUEST(1),NEW(2),LOGIN(3),BAN(4)',
  `login_count` int(11) NOT NULL DEFAULT '0' COMMENT '玩家总的登陆次数',
  `continuous_login_count` int(11) DEFAULT '0' COMMENT '连续登陆次数',
  `lastLogin_time` int(11) DEFAULT '0' COMMENT '上次登录时间',
  `lastlogout_time` int(11) NOT NULL DEFAULT '0' COMMENT '上次下线时间',
  `is_adult` bit(1) NOT NULL DEFAULT b'1' COMMENT '是否成年',
  `newbie_guide` int(11) DEFAULT '0' COMMENT '新手引导ID',
  `xinkai` float(11,2) DEFAULT '0.00' COMMENT '新开服是否领取奖励',
  `xinkai1` float(11,2) DEFAULT '0.00',
  `xinkai2` float(11,2) DEFAULT '0.00',
  `is_turnover` bit(1) DEFAULT b'0' COMMENT '是否流逝',
  `is_firsttimethatcard` bit(1) NOT NULL DEFAULT b'1' COMMENT '是否第一次抽卡',
  `is_cardto10` tinyint(3) DEFAULT '0',
  `is_hthemeweek` tinyint(3) DEFAULT '0',
  `all_buytimes` varchar(50) DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='玩家基础 属性表';
